CREATE DATABASE NETOBET;

USE NETOBET; 

--(Login, Senha, Telefone, Email, Nome, CPF)
CREATE TABLE USUARIOS (
    CD_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    NM_NOME VARCHAR(100) NOT NULL,
    NM_EMAIL VARCHAR(50) NOT NULL,
    SENHA_USUARIO VARCHAR(26) NOT NULL,
    NR_TELEFONE INT(11) NULL,
    NR_CPF VARCHAR(11) NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT GETDATE() 
    CONSTRAINT NR_CPF UNIQUE (CPF)
    CONSTRAINT NM_EMAIL UNIQUE (CPF)
);

CREATE PROCEDURE INSERIR_USUARIO
    @NOME VARCHAR(100), 
    @EMAIL VARCHAR(50),
    @SENHA VARCHAR(26),
    @TELEFONE INT(11),
    @CPF VARCHAR(11)
AS
BEGIN
    IF CPF IN (SELECT NR_CPF FROM USUARIOS) OR EMAIL IN (SELECT NM_EMAIL FROM USUARIOS)
        BEGIN
            SELECT 'CPF ou Email já cadastrados' AS Mensagem;
        END
    ELSE
        BEGIN
            INSERT INTO USUARIOS (NM_NOME, NM_EMAIL, SENHA_USUARIO , NR_TELEFONE, NR_CPF)
            VALUES (@NOME, @EMAIL, @SENHA, @TELEFONE, @CPF);
        END
END;    